//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hasher.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hasher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die .checksums ähnelt.
        /// </summary>
        internal static string checksumFileExt {
            get {
                return ResourceManager.GetString("checksumFileExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die : ähnelt.
        /// </summary>
        internal static string colonDelimiter {
            get {
                return ResourceManager.GetString("colonDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die , ähnelt.
        /// </summary>
        internal static string commaDelimiter {
            get {
                return ResourceManager.GetString("commaDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        internal static string dash {
            get {
                return ResourceManager.GetString("dash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This function is experimental and may not provide exact results. ähnelt.
        /// </summary>
        internal static string experimental {
            get {
                return ResourceManager.GetString("experimental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fatcow_arrow_refresh_small_16 {
            get {
                object obj = ResourceManager.GetObject("fatcow_arrow_refresh_small_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fatcow_clipboard_empty_16 {
            get {
                object obj = ResourceManager.GetObject("fatcow_clipboard_empty_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fatcow_diskette_16 {
            get {
                object obj = ResourceManager.GetObject("fatcow_diskette_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fatcow_document_hash_tag_16 {
            get {
                object obj = ResourceManager.GetObject("fatcow_document_hash_tag_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fatcow_infomation_16 {
            get {
                object obj = ResourceManager.GetObject("fatcow_infomation_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fatcow_page_16 {
            get {
                object obj = ResourceManager.GetObject("fatcow_page_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fatcow_page_save_16 {
            get {
                object obj = ResourceManager.GetObject("fatcow_page_save-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fatcow_paste_plain_16 {
            get {
                object obj = ResourceManager.GetObject("fatcow_paste_plain_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fatcow_text_effects_16 {
            get {
                object obj = ResourceManager.GetObject("fatcow_text_effects_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fatfow_tubes_16 {
            get {
                object obj = ResourceManager.GetObject("fatfow_tubes_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File does not exist. ähnelt.
        /// </summary>
        internal static string fileDoesNotExist {
            get {
                return ResourceManager.GetString("fileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Information ähnelt.
        /// </summary>
        internal static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo_hasher_96 {
            get {
                object obj = ResourceManager.GetObject("logo-hasher-96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MD5 ähnelt.
        /// </summary>
        internal static string md5 {
            get {
                return ResourceManager.GetString("md5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die .md5 ähnelt.
        /// </summary>
        internal static string md5FileExt {
            get {
                return ResourceManager.GetString("md5FileExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Only a file or a text are accepted. ähnelt.
        /// </summary>
        internal static string onlyFileOrTextAreAccepted {
            get {
                return ResourceManager.GetString("onlyFileOrTextAreAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Only the first file of multiple files is accepted. ähnelt.
        /// </summary>
        internal static string onlyFirstFileIsAccepted {
            get {
                return ResourceManager.GetString("onlyFirstFileIsAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die | ähnelt.
        /// </summary>
        internal static string pipeDelimiter {
            get {
                return ResourceManager.GetString("pipeDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die RIPEMD160 ähnelt.
        /// </summary>
        internal static string ripemd160 {
            get {
                return ResourceManager.GetString("ripemd160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die .ripemd160 ähnelt.
        /// </summary>
        internal static string ripemd160FileExt {
            get {
                return ResourceManager.GetString("ripemd160FileExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Saved. ähnelt.
        /// </summary>
        internal static string saved {
            get {
                return ResourceManager.GetString("saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ; ähnelt.
        /// </summary>
        internal static string semicolonDelimiter {
            get {
                return ResourceManager.GetString("semicolonDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SHA1 ähnelt.
        /// </summary>
        internal static string sha1 {
            get {
                return ResourceManager.GetString("sha1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die .sha1 ähnelt.
        /// </summary>
        internal static string sha1FileExt {
            get {
                return ResourceManager.GetString("sha1FileExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SHA256 ähnelt.
        /// </summary>
        internal static string sha256 {
            get {
                return ResourceManager.GetString("sha256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die .sha256 ähnelt.
        /// </summary>
        internal static string sha256FileExt {
            get {
                return ResourceManager.GetString("sha256FileExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SHA384 ähnelt.
        /// </summary>
        internal static string sha384 {
            get {
                return ResourceManager.GetString("sha384", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die .sha384 ähnelt.
        /// </summary>
        internal static string sha384FileExt {
            get {
                return ResourceManager.GetString("sha384FileExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SHA512 ähnelt.
        /// </summary>
        internal static string sha512 {
            get {
                return ResourceManager.GetString("sha512", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die .sha512 ähnelt.
        /// </summary>
        internal static string sha512FileExt {
            get {
                return ResourceManager.GetString("sha512FileExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die   ähnelt.
        /// </summary>
        internal static string spaceDelimiter {
            get {
                return ResourceManager.GetString("spaceDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die \t ähnelt.
        /// </summary>
        internal static string tabDelimiter {
            get {
                return ResourceManager.GetString("tabDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning ähnelt.
        /// </summary>
        internal static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
    }
}
