//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Runtime.CompilerServices;

namespace Numeric_List_Generator.Properties {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    internal sealed partial class Settings : ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool userStayOnTop {
            get {
                return ((bool)(this["userStayOnTop"]));
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool systemStayOnTop {
            get {
                return ((bool)(this["systemStayOnTop"]));
            }
            set {
                this["systemStayOnTop"] = value;
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool userMinimizeToTray {
            get {
                return ((bool)(this["userMinimizeToTray"]));
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool systemMinimizeToTray {
            get {
                return ((bool)(this["systemMinimizeToTray"]));
            }
            set {
                this["systemMinimizeToTray"] = value;
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool userEnableVisualStyle {
            get {
                return ((bool)(this["userEnableVisualStyle"]));
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool systemEnableVisualStyle {
            get {
                return ((bool)(this["systemEnableVisualStyle"]));
            }
            set {
                this["systemEnableVisualStyle"] = value;
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool userEnableStatusbarSize {
            get {
                return ((bool)(this["userEnableStatusbarSize"]));
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool systemEnableStatusbarSize {
            get {
                return ((bool)(this["systemEnableStatusbarSize"]));
            }
            set {
                this["systemEnableStatusbarSize"] = value;
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool userEnableStatusbarLines {
            get {
                return ((bool)(this["userEnableStatusbarLines"]));
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool systemEnableStatusbarLines {
            get {
                return ((bool)(this["systemEnableStatusbarLines"]));
            }
            set {
                this["systemEnableStatusbarLines"] = value;
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool userEnableStatusbarTimespan {
            get {
                return ((bool)(this["userEnableStatusbarTimespan"]));
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool systemEnableStatusbarTimespan {
            get {
                return ((bool)(this["systemEnableStatusbarTimespan"]));
            }
            set {
                this["systemEnableStatusbarTimespan"] = value;
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool userEnableStatusbarLIM {
            get {
                return ((bool)(this["userEnableStatusbarLIM"]));
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool systemEnableStatusbarLIM {
            get {
                return ((bool)(this["systemEnableStatusbarLIM"]));
            }
            set {
                this["systemEnableStatusbarLIM"] = value;
            }
        }
    }
}
